import { Head, router, useForm, usePage } from '@inertiajs/react';
import { Bot, Copy, Loader2, MessageCircleMore, UserPlus } from 'lucide-react';
import { FormEvent, useState } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import type { Campaign, Lead, SharedProps } from '../../types';

type Props = { leads: Lead[]; campaigns: Campaign[] };

export default function Leads({ leads, campaigns }: Props) {
    const { props } = usePage<SharedProps>();
    const aiConfigured = Boolean(props.aiConfigured);
    const [scoringId,setScoringId]=useState<number|null>(null);
    const [copied,setCopied]=useState<number|null>(null);
    const form=useForm({ name:'', phone:'', company:'', business_type:'', source:'whatsapp', marketing_campaign_id:'', notes:'' });
    const submit=(e:FormEvent)=>{e.preventDefault();form.post('/leads',{preserveScroll:true,onSuccess:()=>form.reset('name','phone','company','business_type','marketing_campaign_id','notes')});};
    const score=(id:number)=>{setScoringId(id);router.post(`/leads/${id}/score`,{}, {preserveScroll:true,onFinish:()=>setScoringId(null)});};
    const copy=async(lead:Lead)=>{if(!lead.whatsapp_script)return;await navigator.clipboard.writeText(lead.whatsapp_script);setCopied(lead.id);setTimeout(()=>setCopied(null),1200);};

    return <AppLayout title="Prospects" subtitle="Centralise les leads, laisse l’IA prioriser les opportunités, puis utilise les recommandations pour préparer la prise de contact." actions={<div className={`rounded-full border px-3 py-2 text-xs font-bold ${aiConfigured?'border-emerald-800 text-emerald-300':'border-amber-800 text-amber-300'}`}>{aiConfigured?'Scoring IA actif':'IA non configurée'}</div>}>
        <Head title="Prospects" />
        <div className="grid gap-6 xl:grid-cols-[380px_1fr]">
            <section className="panel h-fit p-5"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-amber-400 p-2 text-slate-950"><UserPlus size={18}/></div><div><h2 className="font-bold">Ajouter un prospect</h2><p className="text-xs text-slate-500">Saisie manuelle / WhatsApp.</p></div></div><form className="space-y-4" onSubmit={submit}><div><label className="label">Nom</label><input className="field" value={form.data.name} onChange={e=>form.setData('name',e.target.value)} required/></div><div><label className="label">WhatsApp / téléphone</label><input className="field" value={form.data.phone} onChange={e=>form.setData('phone',e.target.value)} required/></div><div className="grid grid-cols-2 gap-3"><div><label className="label">Entreprise</label><input className="field" value={form.data.company} onChange={e=>form.setData('company',e.target.value)}/></div><div><label className="label">Activité</label><input className="field" value={form.data.business_type} onChange={e=>form.setData('business_type',e.target.value)}/></div></div><div><label className="label">Source</label><select className="field" value={form.data.source} onChange={e=>form.setData('source',e.target.value)}>{['whatsapp','facebook','instagram','tiktok','linkedin','manual'].map(v=><option key={v}>{v}</option>)}</select></div><div><label className="label">Campagne</label><select className="field" value={form.data.marketing_campaign_id} onChange={e=>form.setData('marketing_campaign_id',e.target.value)}><option value="">Aucune</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><label className="label">Notes / besoin détecté</label><textarea className="field min-h-24" value={form.data.notes} onChange={e=>form.setData('notes',e.target.value)}/></div><button className="btn-primary w-full" disabled={form.processing}>{form.processing&&<Loader2 size={16} className="animate-spin"/>}Enregistrer</button></form></section>

            <section className="space-y-4">{leads.map(lead=><article key={lead.id} className="panel p-5"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black">{lead.name}</h2><span className="rounded-full bg-slate-800 px-2.5 py-1 text-[10px] font-black uppercase text-slate-300">{lead.status}</span></div><div className="mt-1 text-xs text-slate-500">{lead.company || lead.business_type || 'Entreprise non précisée'} · {lead.source} · {lead.phone}</div></div><div className="text-right"><div className="text-3xl font-black text-amber-300">{lead.score}<span className="text-xs text-slate-600">/100</span></div><button className="mt-2 inline-flex items-center gap-1.5 text-xs font-bold text-amber-300 disabled:text-slate-600" disabled={!aiConfigured||scoringId===lead.id} onClick={()=>score(lead.id)}>{scoringId===lead.id?<Loader2 size={14} className="animate-spin"/>:<Bot size={14}/>}Qualifier avec l’IA</button></div></div>{lead.notes&&<p className="mt-4 text-sm leading-6 text-slate-400">{lead.notes}</p>}{lead.ai_summary&&<div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-slate-800 bg-slate-950/60 p-4"><div className="mb-2 text-[10px] font-black uppercase tracking-wider text-slate-500">Analyse IA</div><p className="text-sm leading-6 text-slate-300">{lead.ai_summary}</p></div><div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><div className="mb-2 text-[10px] font-black uppercase tracking-wider text-amber-300">Prochaine action</div><p className="text-sm leading-6 text-amber-50">{lead.ai_next_action}</p></div></div>}{lead.whatsapp_script&&<div className="mt-3 rounded-xl border border-emerald-800/40 bg-emerald-950/30 p-4"><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-emerald-300"><MessageCircleMore size={15}/>Message WhatsApp proposé</div><button onClick={()=>copy(lead)} className="inline-flex items-center gap-1 text-xs font-bold text-emerald-300"><Copy size={13}/>{copied===lead.id?'Copié':'Copier'}</button></div><p className="whitespace-pre-wrap text-sm leading-6 text-slate-300">{lead.whatsapp_script}</p></div>}</article>)}{leads.length===0&&<div className="panel p-12 text-center text-sm text-slate-500">Aucun prospect enregistré.</div>}</section>
        </div>
    </AppLayout>;
}
